language: php

php:
  - '5.6'
  - '7.1'
env:
  global:
    - NODE_VERSION=8.9.3
    - NPM_VERSION=^6.3.0
    - BUILD_LEADER_ID=4
  matrix:
    - XDEBUG_VERSION=2.5.5

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - pecl channel-update pecl.php.net
  - pecl install xdebug-$XDEBUG_VERSION
  - phpenv config-add travis-php.ini
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g npm@$NPM_VERSION --depth 0

install:
  - npm ci

script:
  - npm run build
  - npm run lint
  - npm run cover

after_success:
  - ./node_modules/.bin/nyc report --reporter=json
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: test
      os: osx
      osx_image: xcode11.2
      language: generic
      before_install:
        # Fix ruby error https://github.com/Homebrew/brew/issues/3299
        - brew update
        - brew install php@7.1
        - brew link --force --overwrite php@7.1
        - mkdir -p /usr/local/etc/php/7.1/conf.d
        - cp travis-php.ini /usr/local/etc/php/7.1/conf.d/
        # see per https://javorszky.co.uk/2018/05/03/getting-xdebug-working-on-php-7-2-and-homebrew/
        # avoid problems with brew's symlink and pecl's recursive mkdir
        - ls -l /usr/local/Cellar/php@7.1/
        - rm /usr/local/Cellar/php@7.1/7.1.33/pecl
        - pecl install xdebug-$XDEBUG_VERSION
        # make xdebug.so available at pecl's expected location
        - ln -s /usr/local/Cellar/php@7.1/7.1.33/pecl/ /usr/local/lib/php/pecl
        - php -i
        - source ~/.nvm/nvm.sh
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - npm install -g npm@$NPM_VERSION --depth 0
    - stage: release
      language: node_js
      node_js: '8'
      before_install: skip
      install:
        - npm install -g npm@$NPM_VERSION
        - npm ci
      script:
        - npm run build
        - npm run semantic-release
      after_success: skip

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
