language: php

php:
  - '5.6'
  - '7.0'

env:
  global:
    - NODE_VERSION=7.9.0
    - NPM_VERSION=^5.0.0
    - BUILD_LEADER_ID=3
  matrix:
    - XDEBUG_VERSION=2.5.5

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - pecl install xdebug-$XDEBUG_VERSION
  - phpenv config-add travis-php.ini
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g npm@$NPM_VERSION --depth 0
  - npm config -g set progress false

install:
  - npm install

script:
  - npm run build
  - npm run lint
  - npm run cover

after_success:
  - 'nyc report --reporter=lcov > coverage.lcov && bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info'

jobs:
  include:
    - stage: release
      language: node_js
      node_js: '8'
      before_install: skip
      install:
        - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
        - git fetch --tags
        - npm install
      script:
        - npm run build
      after_success:
        - npm run semantic-release

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

