version: '{build}'

platform:
  - x64

cache:
  - '%APPDATA%\npm-cache'

environment:
  matrix:
    - {PHP_VERSION: '7.0.20', VC_VERSION: '14', XDEBUG_VERSION: '2.5.5'}
    - {PHP_VERSION: '5.6.30', VC_VERSION: '11', XDEBUG_VERSION: '2.5.5'}

install:
  - ps: . .\appveyor-install.ps1

build_script:
  - npm run compile --silent

test_script:
  - npm run lint --silent
  - npm test --silent

after_test:
  - ps: |
      node_modules\.bin\nyc report --reporter=lcov
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage\lcov.info"
